name: sinergista
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.0
  intl: ^0.19.0
  provider: ^6.1.1
  lucide_icons: ^0.257.0
  flutter_svg: ^2.0.9
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  uuid: ^4.5.1
  image_picker: ^1.2.1
  file_picker: ^8.1.4
  google_generative_ai: ^0.4.6
  syncfusion_flutter_pdf: ^28.1.33
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#2C3E50"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true
